const Productdata = [
  {
    id: 1,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    Status: 0,
    coverCode: "Cover Code",
    coverName: "Cover Name",
    policyType: "Policy Type",
    action: 1,
  },
  {
    id: 2,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    Status: 1,
    coverCode: "Cover Code",
    coverName: "Cover Name",
    policyType: "Policy Type",
    action: 2,
  },
  {
    id: 3,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    Status: 0,
    coverCode: "Cover Code",
    coverName: "Cover Name",
    policyType: "Policy Type",
    action: 3,
  },
  {
    id: 4,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    Status: 1,
    coverCode: "Cover Code",
    coverName: "Cover Name",
    policyType: "Policy Type",
    action: 4,
  },
  {
    id: 5,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    Status: 0,
    coverCode: "Cover Code",
    coverName: "Cover Name",
    policyType: "Policy Type",
    action: 5,
  },
  {
    id: 6,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    Status: 1,
    coverCode: "Cover Code",
    coverName: "Cover Name",
    policyType: "Policy Type",
    action: 6,
  },
  {
    id: 7,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    Status: 0,
    coverCode: "Cover Code",
    coverName: "Cover Name",
    policyType: "Policy Type",
    action: 7,
  },
  {
    id: 8,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    Status: 1,
    coverCode: "Cover Code",
    coverName: "Cover Name",
    policyType: "Policy Type",
    action: 8,
  },
  {
    id: 9,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    Status: 0,
    coverCode: "Cover Code",
    coverName: "Cover Name",
    policyType: "Policy Type",
    action: 9,
  },
  {
    id: 10,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    Status: 0,
    coverCode: "Cover Code",
    coverName: "Cover Name",
    policyType: "Policy Type",
    action: 10,
  },
];
export default Productdata;
