const Productdata = [
  {
    id: 1,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    status: 0,
    insuranceCompanyCode: "Inscom00123",
    insuranceCompanyName: "Informative explanation",
    email: "zealinsurance@abc.com",
    phoneNumber: "9874563210",
    action: "",
  },
  {
    id: 2,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    status: 1,
    insuranceCompanyCode: "Inscom00123",
    insuranceCompanyName: "Informative explanation",
    email: "zealinsurance@abc.com",
    phoneNumber: "9874563210",
    action: "",
  },
  {
    id: 3,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    status: 0,
    insuranceCompanyCode: "Inscom00123",
    insuranceCompanyName: "Informative explanation",
    email: "zealinsurance@abc.com",
    phoneNumber: "9874563210",
    action: "",
  },
  {
    id: 4,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    status: 1,
    insuranceCompanyCode: "Inscom00123",
    insuranceCompanyName: "Informative explanation",
    email: "zealinsurance@abc.com",
    phoneNumber: "9874563210",
    action: "",
  },
  {
    id: 5,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    status: 0,
    insuranceCompanyCode: "Inscom00123",
    insuranceCompanyName: "Informative explanation",
    email: "zealinsurance@abc.com",
    phoneNumber: "9874563210",
    action: "",
  },
  {
    id: 6,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    status: 1,
    insuranceCompanyCode: "Inscom00123",
    insuranceCompanyName: "Informative explanation",
    email: "zealinsurance@abc.com",
    phoneNumber: "9874563210",
    action: "",
  },
  {
    id: 7,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    status: 0,
    insuranceCompanyCode: "Inscom00123",
    insuranceCompanyName: "Informative explanation",
    email: "zealinsurance@abc.com",
    phoneNumber: "9874563210",
    action: "",
  },
  {
    id: 8,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    status: 1,
    insuranceCompanyCode: "Inscom00123",
    insuranceCompanyName: "Informative explanation",
    email: "zealinsurance@abc.com",
    phoneNumber: "9874563210",
    action: "",
  },
  {
    id: 9,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    status: 0,
    insuranceCompanyCode: "Inscom00123",
    insuranceCompanyName: "Informative explanation",
    email: "zealinsurance@abc.com",
    phoneNumber: "9874563210",
    action: "",
  },
  {
    id: 10,
    modifiedby: "Name",
    modifiedOn: "12/12/2023",
    status: 0,
    insuranceCompanyCode: "Inscom00123",
    insuranceCompanyName: "Informative explanation",
    email: "zealinsurance@abc.com",
    phoneNumber: "9874563210",
    action: "",
  },
];
export default Productdata;
