export const data = [
  {
    id: 1,
    branchCode: "0102",
    customerName: "Johnson",
    departmentCode: "0102",
    receiptNo: "0102",
    receiptDate: "10/10/2023",
    paymentType: "Cash",
    amount: "5000",
    action: "Action",
  },
    {
      id: 1,
      branchCode: "0102",
      customerName: "Johnson",
      departmentCode: "0102",
      receiptNo: "0102",
      receiptDate: "10/10/2023",
      paymentType: "Cash",
      amount: "5000",
      action: "Action",
    },
      {
        id: 1,
        branchCode: "0102",
        customerName: "Johnson",
        departmentCode: "0102",
        receiptNo: "0102",
        receiptDate: "10/10/2023",
        paymentType: "Cash",
        amount: "5000",
        action: "Action",
      },
      {
        id: 1,
        branchCode: "0102",
        customerName: "Johnson",
        departmentCode: "0102",
        receiptNo: "0102",
        receiptDate: "10/10/2023",
        paymentType: "Cash",
        amount: "5000",
        action: "Action",
      },
      {
        id: 1,
        branchCode: "0102",
        customerName: "Johnson",
        departmentCode: "0102",
        receiptNo: "0102",
        receiptDate: "10/10/2023",
        paymentType: "Cash",
        amount: "5000",
        action: "Action",
      },
      {
        id: 1,
        branchCode: "0102",
        customerName: "Johnson",
        departmentCode: "0102",
        receiptNo: "0102",
        receiptDate: "10/10/2023",
        paymentType: "Cash",
        amount: "5000",
        action: "Action",
      },
      {
        id: 1,
        branchCode: "0102",
        customerName: "Johnson",
        departmentCode: "0102",
        receiptNo: "0102",
        receiptDate: "10/10/2023",
        paymentType: "Cash",
        amount: "5000",
        action: "Action",
      },
      {
        id: 1,
        branchCode: "0102",
        customerName: "Johnson",
        departmentCode: "0102",
        receiptNo: "0102",
        receiptDate: "10/10/2023",
        paymentType: "Cash",
        amount: "5000",
        action: "Action",
      },
      {
        id: 1,
        branchCode: "0102",
        customerName: "Johnson",
        departmentCode: "0102",
        receiptNo: "0102",
        receiptDate: "10/10/2023",
        paymentType: "Cash",
        amount: "5000",
        action: "Action",
      },
      {
        id: 1,
        branchCode: "0102",
        customerName: "Johnson",
        departmentCode: "0102",
        receiptNo: "0102",
        receiptDate: "10/10/2023",
        paymentType: "Cash",
        amount: "5000",
        action: "Action",
      },
      {
        id: 1,
        branchCode: "0102",
        customerName: "Johnson",
        departmentCode: "0102",
        receiptNo: "0102",
        receiptDate: "10/10/2023",
        paymentType: "Cash",
        amount: "5000",
        action: "Action",
      },
      {
        id: 1,
        branchCode: "0102",
        customerName: "Johnson",
        departmentCode: "0102",
        receiptNo: "0102",
        receiptDate: "10/10/2023",
        paymentType: "Cash",
        amount: "5000",
        action: "Action",
      },
   
  ];
  