export const LOGIN = "login/LOGIN";
export const LOGOUT = "login/LOGOUT";
export const GET_JOURNAL_VOUCHER = 'journalvoucher/GET_JOURNAL_VOUCHER'
export const GET_POST_TABEL_JOURNAL_VOUCHER = 'journalvoucher/GET_POST_TABEL_JOURNAL_VOUCHER'

export const GET_PAYMENT_VOUCHER = "journalvoucher/GET_PAYMENT_VOUCHER";
export const GET_PAYMENT_VOUCHER_BY_ID =
  "journalvoucher/GET_PAYMENT_VOUCHER_BY_ID";
export const PATCH_PAYMENT_STATUS_BY_ID =
  "paymentvoucher/PATCH_PAYMENT_STATUS_BY_ID";
export const POST_PAYMENT_VOUCHER_CREATE_DATA =
  "paymentvoucher/POST_PAYMENT_VOUCHER_CREATE_DATA";
export const GET_CHECK_BOOK_DETAILS = "paymentvoucher/GET_CHECK_BOOK_DETAILS";
export const GET_PAYMENT_CHECKBOK_DETAILS =
  "paymentvoucher/GET_PAYMENT_CHECKBOK_DETAILS";
export const PATCH_INVOICE_LIST_DETAILS =
  "paymentvoucher/GET_PAYMENT_CHECKBOK_DETAILS";

export const GET_COMMISSION = "commission/GET_COMMISSION";
export const GET_TAXATION = "taxation/GET_TAXATION";
export const GET_SUB__ACCOUNT = "subaccount/GET_SUB__ACCOUNT";
export const POST_ADD_PETTY_CASH = "pettycash/POST_ADD_PETTY_CASH";

export const GET_COMMISSION_BY_ID = "commission/GET_COMMISSION_BY_ID"
export const GET_COMMISSION_SEARCH_LIST = 'commission/GET_COMMISSION_SEARCH_LIST'
export const POST_COMMISSION = 'commission/POST_COMMISSION'
export const GET_COMMISSION_VIEW = 'commission/GET_COMMISSION_VIEW'
export const PATCH_COMMISSION_EDIT = 'commission/PATCH_COMMISSION_EDIT'

export const GET_TAXATION_BY_ID = "taxation/GET_TAXATION_BY_ID";
export const GET_TAXATION_SEARCH_LIST = 'taxation/GET_TAXATION_SEARCH_LIST'
export const POST_TAXATION = 'taxation/POST_TAXATION'
export const GET_TAXATION_VIEW = 'taxation/GET_TAXATION_VIEW'
export const PATCH_TAXATION_EDIT = 'taxation/PATCH_TAXATION_EDIT'

export const GET_PETTY_CASH_BY_ID = "pettycash/GET_PETTY_CASH_BY_ID";
export const GET_PETTY_CASH_SEARCH_LIST = 'pettycash/GET_PETTY_CASH_SEARCH_LIST'
export const POST_PETTY_CASH = 'pettycash/POST_PETTY_CASH'
export const GET_PETTY_CASH_VIEW = 'pettycash/GET_PETTY_CASH_VIEW'
export const PATCH_PETTY_CASH_EDIT = 'pettycash/PATCH_PETTY_CASH_EDIT'

export const GET_SUB__ACCOUNT_BY_ID = "subaccount/GET_SUB__ACCOUNT_BY_ID";
// export const GET_PETTY_CASH_BY_ID="pettycash/GET_PETTY_CASH_BY_ID"
// export const GET_SUB_ACCOUNT_SEARCH_LIST = 'subaccount/GET_SUB_ACCOUNT_SEARCH_LIST'
// export const  POST_SUB__ACCOUNT = 'subaccount/POST_SUB__ACCOUNT'
// export const  GET_SUB__ACCOUNT_VIEW = 'subaccount/GET_SUB__ACCOUNT_VIEW'
// export const  PATCH_SUB__ACCOUNT_EDIT = 'subaccount/PATCH_SUB__ACCOUNT_EDIT'

export const GET_TRANSACTION_CODE_LIST = 'transaction/GET_TRANSACTION_CODE_LIST'
export const GET_TRANSACTION_CODE_LIST_SEARCH = 'transaction/GET_TRANSACTION_CODE_LIST_SEARCH'
export const POST_STATUS = 'transaction/POST_STATUS'
export const POST_ADD_TRANSACTION = 'transaction/POST_ADD_TRANSACTION'
export const GET_TRANSACTION_CODE_SETUP = 'transaction/GET_TRANSACTION_CODE_SETUP'
export const GET_USER_GROUP_ACCESS = 'transaction/GET_USER_GROUP_ACCESS'
export const POST_ADD_TRANSACTION_CODE_SETUP = 'transaction/POST_TRANSACTION_CODE_SETUP'
export const POST_ADD_USER_GROUP_ACCESS = 'transaction/POST_USER_GROUP_ACCESS'
export const GET_TRANSACTION_CODE_DETAILS_VIEW = 'transaction/GET_TRANSACTION_CODE_DETAILS_VIEW'
export const PATCH_TRANSACTION_CODE_DETAILS_EDIT = 'transaction/PATCH_TRANSACTION_CODE_DETAILS_EDIT'

export const GET_CURRENCY_LIST = 'currency/GET_CURRENCY_LIST'
export const GET_CURRENCY_SEARCH_LIST = 'currency/GET_CURRENCY_SEARCH_LIST'
export const POST_CURRENCY_STATUS = 'currency/POST_CURRENCY_STATUS'
export const GET_CURRENCY_DETAIL_VIEW = 'currency/GET_CURRENCY_DETAIL_VIEW'
export const GET_ADD_CURRENCY = 'currency/GET_ADD_CURRENCY'
export const PATCH_CURRENCY_DETAIL_EDIT = 'currency/PATCH_CURRENCY_DETAIL_EDIT'

export const GET_EXCHANGE_LIST = 'exchange/GET_EXCHANGE_LIST'
export const GET_EXCHANGE_SEARCH_LIST = 'exchange/GET_EXCHANGE_SEARCH_LIST'
export const POST_EXCHANGE_STATUS = 'exchange/POST_EXCHANGE_STATUS'
export const GET_EXCHANGE_DETAIL_VIEW = 'exchange/GET_EXCHANGE_DETAIL_VIEW'
export const GET_ADD_EXCHANGE = 'exchange/GET_ADD_EXCHANGE'
export const PATCH_EXCHANGE_DETAIL_EDIT = 'exchange/PATCH_EXCHANGE_DETAIL_EDIT'

export const GET_BANK_LIST = 'bank/GET_BANK_LIST'
export const GET_BANK_SEARCH_LIST = 'bank/GET_BANK_SEARCH_LIST'
export const POST_BANK_STATUS = 'bank/POST_BANK_STATUS'
export const GET_BANK_DETAIL_VIEW = 'bank/GET_BANK_DETAIL_VIEW'
export const GET_ADD_BANK = 'bank/GET_ADD_BANK'
export const PATCH_BANK_DETAIL_EDIT = 'bank/PATCH_BANK_DETAIL_EDIT'

export const GET_ACCOUNT_CATEGORY_LIST = 'accountCategory/GET_ACCOUNT_CATEGORY_LIST'
export const GET_ACCOUNT_CATEGORY_SEARCH_LIST = 'accountCategory/GET_ACCOUNT_CATEGORY_SEARCH_LIST'
export const POST_ACCOUNT_CATEGORY_STATUS = 'accountCategory/POST_ACCOUNT_CATEGORY_STATUS'
export const GET_ACCOUNT_CATEGORY_DETAIL_VIEW = 'accountCategory/GET_ACCOUNT_CATEGORY_DETAIL_VIEW'
export const GET_ADD_ACCOUNT_CATEGORY = 'accountCategory/GET_ADD_ACCOUNT_CATEGORY'
export const PATCH_ACCOUNT_CATEGORY_DETAIL_EDIT = 'accountCategory/PATCH_ACCOUNT_CATEGORY_DETAIL_EDIT'

export const GET_MAIN_ACCOUNT_LIST = 'mainAccout/GET_MAIN_ACCOUNT_LIST'
export const GET_MAIN_ACCOUNT_SEARCH_LIST = 'mainAccout/GET_MAIN_ACCOUNT_SEARCH_LIST'
export const POST_MAIN_ACCOUNT_STATUS = 'mainAccout/POST_MAIN_ACCOUNT_STATUS'
export const GET_MAIN_ACCOUNT_DETAIL_VIEW = 'mainAccout/GET_MAIN_ACCOUNT_DETAIL_VIEW'
export const GET_ADD_MAIN_ACCOUNT = 'mainAccout/GET_ADD_MAIN_ACCOUNT'
export const PATCH_MAIN_ACCOUNT_DETAIL_EDIT = 'mainAccout/PATCH_MAIN_ACCOUNT_DETAIL_EDIT'
export const GET_SUB_ACCOUNT_SEARCH_LIST = 'subaccount/GET_SUB_ACCOUNT_SEARCH_LIST'
export const  POST_SUB__ACCOUNT = 'subaccount/POST_SUB__ACCOUNT'
export const  GET_SUB__ACCOUNT_VIEW = 'subaccount/GET_SUB__ACCOUNT_VIEW'
export const  PATCH_SUB__ACCOUNT_EDIT = 'subaccount/PATCH_SUB__ACCOUNT_EDIT'

export const GET_RECEIPT_DETAILS = 'receipts/GET_RECEIPT_DETAILS'
export const GET_RECEIPT_DETAILS_BY_ID ='receipts/GET_RECEIPT_DETAILS_BY_ID'
export const GET_RECEIVABLE_TABLE ='receipts/GET_RECEIVABLE_TABLE'
export const POST_ADD_RECEIPTS ='receipts/POST_ADD_RECEIPTS'
export const POST_PAYMENT_DETAILS ='receipts/POST_PAYMENT_DETAILS'
export const PATCH_RECEIPT_EDIT ='receipts/PATCH_RECEIPT_EDIT'



export const GET_JOURNAL_VOUCHER_BY_ID = "journalvoucher/GET_JOURNAL_VOUCHER_BY_ID";
export const GET_JOURNAL_VOUCHER_SEARCH_LIST = 'journalvoucher/GET_JOURNAL_VOUCHER_SEARCH_LIST'
export const POST_JOURNAL_VOUCHER = 'journalvoucher/POST_JOURNAL_VOUCHER'
export const POST_ADD_JOURNAL_VOUCHER = 'journalvoucher/POST_ADD_JOURNAL_VOUCHER'
export const GET_JOURNAL_VOUCHER_VIEW = 'journalvoucher/GET_JOURNAL_VOUCHER_VIEW'
export const PATCH_JOURNAL_VOUCHER_EDIT = 'journalvoucher/PATCH_JOURNAL_VOUCHER_EDIT'
export const DELETE_JOURNAL_VOUCHER="journalvoucher/DELETE_JOURNAL_VOUCHER"


export const GET_CORRECTION_JV_LIST= "correction/GET_CORRECTION_JV_LIST";
export const POST_CORRECTION_JV = 'correction/POST_CORRECTION_JV'
export const GET_CORRECTION_JV_VIEW = 'correction/GET_CORRECTION_JV_VIEW'
export const PATCH_CORRECTION_JV_EDIT = 'correction/PATCH_CORRECTION_JV_EDIT'

export const GET_REVERSAL_JV_LIST= "reversal/GET_REVERSAL_JV_LIST";
export const POST_REVERSAL_JV = 'reversal/POST_REVERSAL_JV'
export const GET_REVERSAL_JV_VIEW = 'reversal/GET_REVERSAL_JV_VIEW'
export const PATCH_REVERSAL_JV_EDIT = 'reversal/PATCH_REVERSAL_JV_EDIT'
