export const LOGIN = "login/LOGIN";
export const LOGOUT = "login/LOGOUT";
export const GET_JOURNAL_VOUCHER = 'journalvoucher/GET_JOURNAL_VOUCHER'
export const GET_PAYMENT_VOUCHER = 'journalvoucher/GET_PAYMENT_VOUCHER';
export const GET_PAYMENT_VOUCHER_BY_ID = 'journalvoucher/GET_PAYMENT_VOUCHER_BY_ID';
export const GET_COMMISSION="commission/GET_COMMISSION";
export const GET_COMMISSION_BY_ID="commission/GET_COMMISSION_BY_ID"
export const GET_TAXATION="taxation/GET_TAXATION";
export const GET_TAXATION_BY_ID="taxation/GET_TAXATION_BY_ID";
export const GET_SUB__ACCOUNT="subaccount/GET_SUB__ACCOUNT";
export const GET_SUB__ACCOUNT_BY_ID="subaccount/GET_SUB__ACCOUNT_BY_ID";
export const GET_PETTY_CASH_BY_ID="pettycash/GET_PETTY_CASH_BY_ID"