export const GET_DASHBOARD_DATA = "agent/get/GET_DASHBOARD_DATA";
export const GET_CLIENTS_LIST = 'agent/get/GET_CLIENTS_LIST';
export const GET_UPCOMMING_OPEN_ITEMS_LIST = 'agent/get/GET_UPCOMMING_OPEN_ITEMS_LIST';
export const POST_UPCOMMING_OPEN_ITEMS_LIST="agent/post/POST_UPCOMMING_OPEN_ITEMS_LIST"