const Productdata = [
  {
    id: 1,
    Status: 0,
    vehicleCode: "VC12345",
    vehicleName: "Kia",
    vehicleVariant: "S Series",
    vehicleModel: "Seltos",
    vehicleBrand: "Kia",
    action: 1,
  },
  {
    id: 2,
    Status: 1,
    vehicleCode: "VC12345",
    vehicleName: "Kia",
    vehicleVariant: "S Series",
    vehicleModel: "Seltos",
    vehicleBrand: "Kia",
    action: 2,
  },
  {
    id: 3,
    Status: 0,
    vehicleCode: "VC12345",
    vehicleName: "Kia",
    vehicleVariant: "S Series",
    vehicleModel: "Seltos",
    vehicleBrand: "Kia",
    action: 3,
  },
  {
    id: 4,
    Status: 1,
    vehicleCode: "VC12345",
    vehicleName: "Kia",
    vehicleVariant: "S Series",
    vehicleModel: "Seltos",
    vehicleBrand: "Kia",
    action: 4,
  },
  {
    id: 5,
    Status: 0,
    vehicleCode: "VC12345",
    vehicleName: "Kia",
    vehicleVariant: "S Series",
    vehicleModel: "Seltos",
    vehicleBrand: "Kia",
    action: 5,
  },
  {
    id: 6,
    Status: 1,
    vehicleCode: "VC12345",
    vehicleName: "Kia",
    vehicleVariant: "S Series",
    vehicleModel: "Seltos",
    vehicleBrand: "Kia",
    action: 6,
  },
  {
    id: 7,
    Status: 0,
    vehicleCode: "VC12345",
    vehicleName: "Kia",
    vehicleVariant: "S Series",
    vehicleModel: "Seltos",
    vehicleBrand: "Kia",
    action: 7,
  },
  {
    id: 8,
    Status: 1,
    vehicleCode: "VC12345",
    vehicleName: "Kia",
    vehicleVariant: "S Series",
    vehicleModel: "Seltos",
    vehicleBrand: "Kia",
    action: 8,
  },
  {
    id: 9,
    Status: 0,
    vehicleCode: "VC12345",
    vehicleName: "Kia",
    vehicleVariant: "S Series",
    vehicleModel: "Seltos",
    vehicleBrand: "Kia",
    action: 9,
  },
  {
    id: 10,
    Status: 0,
    vehicleCode: "VC12345",
    vehicleName: "Kia",
    vehicleVariant: "S Series",
    vehicleModel: "Seltos",
    vehicleBrand: "Kia",
    action: 10,
  },
];
export default Productdata;
